### ISSUE TITLE
Window thumbnail dimensions are not updated accordingly

### ISSUE THREAD

**Issue by pesader** [G-dH/window-thumbnails#11]
# Description

When I create a thumbnail for a window, then resize that window, the dimensions of the thumbnail are not updated accordingly. This results in a distorted thumbnail, until I generate a new one using the keyboard shortcut.

Here's how that looks like (notice how the toggles are "stretched"):

[Screencast from 2024-03-24 11-50-37.webm](https://github.com/G-dH/window-thumbnails/assets/65264536/dac90ae0-89a6-4688-aa65-c30b33564e59)

# Steps do Reproduce

1. Enable the extension
2. Create a thumbnail for a window
3. Resize that window
4. You should see the thumbnail getting distorted

# Gratitude

Thanks for developing this extension, it's very fully featured and super useful 🚀🧩

**Comment by G-dH** [comment]
Yeah, that's already on my to-do list.
Thanks!

**Comment by pesader** [comment]
Yes, thank you :)
