### ISSUE TITLE
(Minimize to thumbnail) Middle-clicking the thumbnail causes invisible thumbnail to stay open, leading to crash of GNOME Shell

### ISSUE THREAD

**Issue by 3ship** [G-dH/window-thumbnails#2]
![Screenshot from 2024-03-09 16-01-30](https://github.com/G-dH/window-thumbnails/assets/47889681/91dd0d87-ed39-4665-ac67-4995fa048ada)

EndeavourOS with GNOME 45

Steps to reproduce:

1. Tested with mpv video player
2. Use WTMB's "Minimize to Thumbnail"
3. ~~Right-click the thumbnail to open the Window Preview~~
4. Middle-click the thumbnail to close the application
5. Go into GNOME's Activities overview and back out

Expected behavior:
The mpv window along with all WTMB elements close entirely.

Observed behavior:
The WTMB thumbnail's close button is still visible. An invisible thumbnail is still present and can be interacted with: Right-click to toggle Window Preview shows the blue outline of the former window. The thumbnail's close button doesn't work.
Proceed with caution: Middle-clicking the invisible thumbnail causes GNOME Shell to crash.

edit: I just did some additional tests: I can reproduce this bug on a freshly started GNOME shell with all other extensions deactivated. I can also reproduce it with applications other than mpv. Toggling the Window Preview is actually *not* a condition for the invisible thumbnail to appear.

**Comment by G-dH** [comment]
Thanks, I'll fix it soon.
