### ISSUE TITLE
[BUG] Doesn't display on top of full screen windows, or maximized window without panel

### ISSUE THREAD

**Issue by RushingAlien** [G-dH/window-thumbnails#7]
## Description
Hey it seems that window-thumbnails does not display on top of full screen windows or maximized windows when panel is not present (i.e on non-primary monitor)

## Reproduce
1. make window thumbnail
1. Full screen a window
2. Make sure focus is still on said window
or
1. make window thumbnail
1. Mazimize a window when panel is not present
2. Make sure focus is still on said window

# System Details Report
---

## Report details
- **Date generated:**                              2024-03-13 15:44:43

## Hardware Information:
- **Hardware Model:**                              ADVAN 1701
- **Memory:**                                      16.0 GiB
- **Processor:**                                   AMD Ryzen™ 7 7735HS with Radeon™ Graphics × 16
- **Graphics:**                                    AMD Radeon™ Graphics
- **Disk Capacity:**                               1.0 TB

## Software Information:
- **Firmware Version:**                            6.02
- **OS Name:**                                     Arch Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.4
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.7.9-2-cachyos

**Comment by RushingAlien** [comment]
Could be an upstream bug since it also happens with : 
- https://github.com/icedman/search-light/issues/77
- https://github.com/oae/gnome-shell-pano/issues/263


But i can't say what exactly the bug is, so it can help if you guys can figure out and report if it is upstream

**Comment by RushingAlien** [comment]
That's a pretty temporary solution, consider looking into gnome's notification and alt+f2 shell menu, looking glass too, they all work on full screen windows.

But for now ig I'll enable that the disabel direct scanout extension when i use this extension, thanks

**Comment by RushingAlien** [comment]
are you on x11 or wayland?

**Comment by G-dH** [comment]
Both. However, it seems that using `Meta.disable_unredirect_for_display()` when the thumbnail is on the screen should be the correct solution.

**Comment by G-dH** [comment]
Just a note for others: `Meta.disable_unredirect_for_display(global.display)` calls are being stacked, and each `Meta.enable_unredirect_for_display(global.display)` call works against its corresponding disable counterpart. Therefore, a single `Meta.disable_unredirect_for_display(global.display)` call can globally disable unredirection, even if GNOME Shell manages the enable and disable state for modal dialogs and animations. **So it is important to not call disable repeatedly**.

**Comment by RushingAlien** [comment]
Can confirm that it works. :D  
Thank you

**Comment by RushingAlien** [comment]
Hey, just letting folks know, that once this [merge request](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2660) that allows direct scanout(unredirect) on non-fullscreen clients, this may not need to be done anymore.
